### ISSUE TITLE
ProvideData() not found?

### ISSUE THREAD

**Issue by oSumAtrIX** [OsuSync/OsuRTDataProvider#15]
[15:24:57] [OsuRTDataProviderPlugin]System.MissingMethodException: Methode nicht gefunden: "OsuRTDataProvider.Listen.ProvideData OsuRTDataProvider.Listen.OsuListenerManager.GetCurrentData(OsuRTDataProvider.Listen.ProvideDataMask)".
   bei OsuLiveStatusPanel.SourcesWrapper.ORTDP.RealtimeDataProvideWrapperBase.GetCurrentBeatmap()
   bei OsuLiveStatusPanel.SourcesWrapper.ORTDP.RealtimeDataProvideWrapperBase.TrigListen()
   bei OsuLiveStatusPanel.SourcesWrapper.ORTDP.RealtimeDataProvideWrapperBase.OnCurrentBeatmapChange(Beatmap beatmap)
   bei OsuRTDataProvider.Listen.OsuListenerManager.OnBeatmapChangedEvt.Invoke(Beatmap map)
   bei OsuRTDataProvider.Listen.OsuListenerManager.ListenLoopUpdate()

**Comment by KedamaOvO** [comment]
update [OsuLiveStatusPanel](https://github.com/OsuSync/OsuLiveStatusPanel/releases/tag/v2.3.0)
