### ISSUE TITLE
ORTDP(Ver1.5.7) can not get game mode correctly. Whatever the beatmap is, the mode is Osu.

### ISSUE THREAD

**Issue by Someone999** [OsuSync/OsuRTDataProvider#18]

**Comment by KedamaOvO** [comment]
What is the version of Osu?
Has the ModeFinder initialization been successful?

**Comment by Someone999** [comment]
My Osu should be up-to-date. And all outputs in sync were green or dark green.

**Comment by Someone999** [comment]
This happen after I update ORTDP to 1.5.7

**Comment by Someone999** [comment]
I output the Mode change result:
Unknow->Osu
And alaways be this.

**Comment by KedamaOvO** [comment]
Is Game Mode manually set to Osu?
![image](https://user-images.githubusercontent.com/9410177/66043391-9667af80-e551-11e9-899f-7fbdf73ea079.png)

**Comment by Someone999** [comment]
Maybe. But I don't remember I did that.

**Comment by Someone999** [comment]
I'll check the setting tomorrow.

**Comment by Someone999** [comment]
That's work after update to ortdp 1.5.8
