### ISSUE TITLE
New Event: Cursor Data

### ISSUE THREAD

**Issue by l3lackShark** [OsuSync/OsuRTDataProvider#20]
Is it possible to add an event for raw cursor coordinates? (with TourneyMode support, if possible) (and HTTP API please)

**Comment by l3lackShark** [comment]
Here are the signatures for cutting edge:
89 50 04 8B E5 5D C2 08 00 Height
89 08 89 50 04 8B E5 5D C2 08 00 Width

**Comment by l3lackShark** [comment]
Attach debugger to these: 
89 50 04 8B E5 5D C2 08 00 CC CC CC CC CC CC CC CC CC CC CC CC CC (Height)
89 08 89 50 04 8B E5 5D C2 08 00 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? CC CC CC CC (Width)

**Comment by l3lackShark** [comment]
Here is the signature: 66 0F D6 07 C6 05 36 61 ?? ?? 00 
Attach debugger in Cheat Engine whenever you are watching replays to get the actual value.

**Comment by KedamaOvO** [comment]
I haven't had time to add new features to ORTDP recently, you can create a PR to the repo.

**Comment by Keytoyze** [comment]
> Here is the signature: 66 0F D6 07 C6 05 36 61 ?? ?? 00
> Attach debugger in Cheat Engine whenever you are watching replays to get the actual value.
> To get Height you do WIDTHADDR+4

Currently replay signature is: 75 0E 33 D2 89 15 ?? ?? ?? ?? 89 15, using the offset 0x34, 0x4, 0x8 and 0x0 to get the head address of replay stream. The raw cursor data is different from the replay address, however.

**Comment by KedamaOvO** [comment]
@l3lackShark released.
