### ISSUE TITLE
Unable to detect mode change during listening

### ISSUE THREAD

**Issue by dora-0** [OsuSync/OsuRTDataProvider#22]
After osu! update `Stable 20191226`, mode change will not be detected until you enter the actual play.
The selected part is the point at which all modes were removed, but is still marked as DT.

![img](https://i.imgur.com/peIISQe.png)

**Comment by KedamaOvO** [comment]
This is because the real-time mods base address is wrong, ORTDP fallback to Playing Mods.
And I have no time recently , so it will be fixed in January.
