### ISSUE TITLE
init PlayFinder Failed! b201912.27.1cuttingedge (same thing with latest stable build)

### ISSUE THREAD

**Issue by OlegSea** [OsuSync/OsuRTDataProvider#23]
[19:10:42] [OsuRTDataProviderPlugin][ID:0]Init PlayFinder Failed! Retry after 3 seconds

**Comment by OlegSea** [comment]
![Sync_4DIWk5ESbt](https://user-images.githubusercontent.com/44728435/71546236-faa9dc00-29a5-11ea-8edc-76cd3f1a653d.png)

**Comment by KedamaOvO** [comment]
https://github.com/OsuSync/RealTimePPDisplayer/issues/52
