### ISSUE TITLE
Score value is -1

### ISSUE THREAD

**Issue by Someone999** [OsuSync/OsuRTDataProvider#24]

**Comment by Someone999** [comment]
![QQ图片20191229192320](https://user-images.githubusercontent.com/45456778/71556234-b2a3bb80-2a70-11ea-84eb-aaa42439e3ef.png)
I think

**Comment by Someone999** [comment]
I don't know if you find, when the Score value abnormal, I check the baseaddress and offset, Score's offset changed. From F4 to F8.

**Comment by KedamaOvO** [comment]
Thanks.

**Comment by Someone999** [comment]
np
