### ISSUE TITLE
[16:58:51] [OsuRTDataProviderPlugin]System.NullReferenceException:

### ISSUE THREAD

**Issue by OlegSea** [OsuSync/OsuRTDataProvider#25]
Stable 20200111.3

**Comment by OlegSea** [comment]
![image](https://user-images.githubusercontent.com/44728435/72205416-bdf4df00-3493-11ea-9953-89eac2048e6d.png)

**Comment by KedamaOvO** [comment]
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.5.12
