### ISSUE TITLE
[OsuRTDataProviderPlugin][ID:0]Init BeatmapFinder Failed! Retry after 3 seconds

### ISSUE THREAD

**Issue by OlegSea** [OsuSync/OsuRTDataProvider#29]
![image](https://user-images.githubusercontent.com/44728435/72447720-e1d36000-37c6-11ea-8360-e3f75a7e226e.png)
Latest patch, mod detection in the menu is disabled

**Comment by OlegSea** [comment]
Oh, i restarted osu!, opened random map and it's fixed

**Comment by MikiraSora** [comment]
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.5.14
now there is a new version was released.
you could backup your Sync and update ORTDP plugin for test.
