### ISSUE TITLE
Can't display acc on tourney client

### ISSUE THREAD

**Issue by SugiuraAyano** [OsuSync/OsuRTDataProvider#30]
Hello! We're trying to use this plugins on tournament because we want to read accuracy and display it.
but when we want to do it. the error message comes up as below:
`[18:52:14] [OsuRTDataProviderPlugin]osu!version compatible condition: 20200116.2 < 20190816 ?
[18:52:14] [OsuRTDataProviderPlugin]Beatmap Base Address (0):0x00000000
[18:52:14] [OsuRTDataProviderPlugin]Beatmap Base Address (1):0x00000000
[18:52:14] [OsuRTDataProviderPlugin][OsuRTDataProvider][ID:1]Init BeatmapFinder Failed! Retry after 3 seconds`
and can't read acc on it.

**Comment by Deliay** [comment]
try 'plugins update'

**Comment by SugiuraAyano** [comment]
I already updated but still can't. Stable, Beta and cutting edge version of osu tourney all can't display acc.

**Comment by SugiuraAyano** [comment]
Now we was found a solution is getting in edit when tourney started. It will found beatmap address like this following video.
https://youtu.be/To9ptIHanE4 
Sorry i can't post video directly.

**Comment by Deliay** [comment]
@KedamaOvO

**Comment by KedamaOvO** [comment]
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.5.14

**Comment by MikiraSora** [comment]
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.5.14
now there is a new version was released.
you could backup your Sync and update ORTDP plugin for test.
@SugiuraAyano

**Comment by SugiuraAyano** [comment]
thanks!
