### ISSUE TITLE
Incorrect display of star rate

### ISSUE THREAD

**Issue by serg220** [OsuSync/OsuRTDataProvider#31]
Hello i have some problem or it's normal?

![image](https://user-images.githubusercontent.com/60229898/73001073-70ce2100-3e34-11ea-8208-90b30ffdb68f.png)
![image](https://user-images.githubusercontent.com/60229898/73001310-d4f0e500-3e34-11ea-85df-98365ab04640.png)

**Comment by MikiraSora** [comment]
Beatmap diff/stars info is calculate&provided by [oppai-ng](https://github.com/Francesco149/oppai-ng).
Our ORTDP plugin just get osu! data and (send to oppai to calculate).
OLSP/Overlay plugins are format&show.

**Comment by serg220** [comment]
ids: 756794, 1020429.
