### ISSUE TITLE
[RealTimePPDisplayer 1.8.7] hit count format problem

### ISSUE THREAD

**Issue by BraveMaster** [OsuSync/OsuRTDataProvider#38]
![screenshot142](https://user-images.githubusercontent.com/49807971/87511169-11dcbc80-c69f-11ea-8e35-5e99dc15bef9.jpg)
This is my hit count format
![ภาพ](https://user-images.githubusercontent.com/49807971/87511238-2de05e00-c69f-11ea-93e9-401f809f2e03.png)

I use Sync 2.18.2 because 2.18.4 can't use command plugins install overlay

**Comment by cyperdark** [comment]
all offsets moved by 0x4
