### ISSUE TITLE
rtpp display/calculation not working

### ISSUE THREAD

**Issue by PotehtoO** [OsuSync/OsuRTDataProvider#40]
Hi, so this probably isn't the right place to post this, but the program was working just recently. But few days ago there was an osu update and after the update the current/real time pp is staying at only 0 and doesn't move. I'm new to using this program so I'm not sure what to do :(
![Mania pp calculation, shows 0 pp for 96% acc play](https://user-images.githubusercontent.com/37375153/87750405-f05e0b00-c82d-11ea-821f-9b19084bcecd.jpg)

**Comment by KedamaOvO** [comment]
try update to OsuRTDataProvider v1.6.4
https://github.com/OsuSync/OsuRTDataProvider/releases/download/v1.6.4/OsuRTDataProvider-1.6.4.zip

**Comment by PotehtoO** [comment]
Yeap, I'd checked back late last night and saw that there was an update and promptly downloaded it, it works now. Thank you!
