### ISSUE TITLE
Playfinder still broken after newest update

### ISSUE THREAD

**Issue by Ocklepod** [OsuSync/OsuRTDataProvider#46]
Not sure whats going on, it worked right after putting new files in Plugin folder, but the next map it suddenly stopped. Also I'm spectating, that might have broken it.

**Comment by MikiraSora** [comment]
could you provide some screenshot and logs file?

**Comment by Ocklepod** [comment]
Not sure i can do that, i just reinstalled entirely and now it's working. I probably broke Playfinder on my own.
