### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.    at OsuRTDataProvider.Listen.OsuListenerManager.ListenLoopUpdate()

### ISSUE THREAD

**Issue by catplays26** [OsuSync/OsuRTDataProvider#48]
System.NullReferenceException: Object reference not set to an instance of an object.
   at OsuRTDataProvider.Listen.OsuListenerManager.ListenLoopUpdate()

Don't have anymore info

**Comment by KedamaOvO** [comment]
#49 49
