### ISSUE TITLE
IngameOverlay does not appear after installing osu! 1012.2 (halloween) update

### ISSUE THREAD

**Issue by asdfqwerty0123** [OsuSync/OsuRTDataProvider#49]
![image](https://user-images.githubusercontent.com/43396722/96131357-0914b480-0f34-11eb-8300-14ca7cc9b97d.png)

As you can see, I set up the rtpp displayer but nothing's displayed in the gray box. This started to happen since I installed osu! version 1012.2 (halloween) update.

Also I got an error message like:
![image](https://user-images.githubusercontent.com/43396722/96131776-935d1880-0f34-11eb-9fcd-bebc85d3c43c.png)

I tried restart osu, restart sync, re-install sync, and none of these worked.

**Comment by KedamaOvO** [comment]
I cannot reproduce the problem. 
It may be that your ORTDP version is too low.

**Comment by KedamaOvO** [comment]
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.6.6

**Comment by asdfqwerty0123** [comment]
yup, it works now after updating ORTDP. Thanks!
