### ISSUE TITLE
Init PlayFinder Failed! Retry after 3 seconds

### ISSUE THREAD

**Issue by cyperdark** [OsuSync/OsuRTDataProvider#6]
OSU Client Verison:b20190828.2 https://i.imgur.com/dhnMfN7.png

**Comment by jackdaguy** [comment]
same problem: 
![image](https://user-images.githubusercontent.com/29892729/64431157-353cef80-d0fd-11e9-8e62-31a7eaf62587.png)
client ver: b20190906.1

**Comment by BraveMaster** [comment]
same problem
![ภาพ](https://user-images.githubusercontent.com/49807971/64467914-321b2100-d148-11e9-8725-e960be692792.png)
![ภาพ](https://user-images.githubusercontent.com/49807971/64467923-44955a80-d148-11e9-8f98-dc80e7fd2a14.png)

**Comment by MikiraSora** [comment]
Currently osu!version ppy add a new mania mod and make ORTDP ModFinder error.
We will notify you after fixed them.
You could use older osu! to play.

**Comment by cyperdark** [comment]
> You could use older osu! to play.
Where can I download the old version?

**Comment by MikiraSora** [comment]
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.4.9

please try this . Just download them and extract to Sync Plugins folder.
@cyperdark  @jackdaguy @BraveMaster

**Comment by cyperdark** [comment]
pp 0.00 https://i.imgur.com/5wBlkmn.gifv

**Comment by MikiraSora** [comment]
@cyperdark Could you provide your Sync zip file / osu! version / plugins info?
for getting plugins info you can type "plugins list" in your Sync.

**Comment by cyperdark** [comment]
lol I rebooted the computer and everything works for me, thanks for the update

**Comment by cyperdark** [comment]
uh, now I started to record replay, and saw this problem https://i.imgur.com/zdwYHxT.png
osu! version: latest
plugins: https://i.imgur.com/OBEfzQq.png

**Comment by MikiraSora** [comment]
Just init failed once because it's probably osu! doesn't get ready.
And next line it show init successfully , so dont worry.
Seeing a bunch of wrong messages is really scary.lol
