### ISSUE TITLE
obtaining Unstable Rate at the end of play

### ISSUE THREAD

**Issue by Acrith** [OsuSync/OsuRTDataProvider#7]
Hello. 
What are the chances that plugin can grab UR out of memory at the end of play, and if such feature development is in progress - what is the current progress?

**Comment by KedamaOvO** [comment]
UR can only be caught in Playing.
I have tried to add UR support. see https://github.com/OsuSync/OsuRTDataProvider/commit/9385e1c79430321caadcf6d4dc907a4a258b0dac

**Comment by KedamaOvO** [comment]
RTPPD has added the ${ur} parameter.
